apiVersion: meta.p6m.dev/v1alpha1
kind: PlatformApplication
metadata:
  name: nextjs-test-frontend
spec:
  config: {}
  # networking:
  #   ingress:
  #     hostnames:
  #       - nobody.alisamji.com
  #     certificate:
  #       externalSecret:
  #         format: pkcs12
  #         secretName: dummy-cert-36-pkcs12
  #         secretStore: alitestbyokv
  #     originRequestRestriction:
  #       headers:
  #         - name: X-Source-Token
  #           value: NotVerySecretToken
  #         - name: X-Forwarded-Host
  #           value: nobody.alisamji.com
