name: Build Branch

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

permissions:
  contents: write # Required for pushing tags

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: p6m-actions/js-pnpm-setup@v1
        with:
          node-version: "20"

      - name: Build
        uses: p6m-actions/js-pnpm-build@v1

  docker-build:
    uses: p6m-dev/github-actions/.github/workflows/build-deploy-docker.yaml@main
    needs:
      - build-and-release

    with:
      registry: ${{ vars.ARTIFACTORY_HOSTNAME }}
      image-name: 'ybor-playground-docker/applications/nextjs-test-frontend'
      context: "."
      dockerfile: ./Dockerfile
      tags: |
        type=ref,event=branch
        type=ref,event=pr
        type=raw,value=latest,enable={{is_default_branch}}
        type=sha
      # linux-arm-runner: ubuntu-24.04-arm-provisioned

    secrets:
      username: ${{ secrets.ARTIFACTORY_USERNAME }}
      password: ${{ secrets.ARTIFACTORY_IDENTITY_TOKEN }}
      secrets: |
        artifactory-token=${{ secrets.ARTIFACTORY_TOKEN }}